tous: creer ordinaire cp flux seek creer2

creer: creer.c
	gcc -Wall -Wextra -g creer.c -o creer

ordinaire: ordinaire.c
	gcc -Wall -Wextra -g ordinaire.c -o ordinaire

cp: cp.c
	gcc -Wall -Wextra -g cp.c -o cp

flux: flux.c
	gcc -Wall -Wextra -g flux.c -o flux

seek: seek.c
	gcc -Wall -Wextra -g seek.c -o seek

.PHONY: tous
